server:
  port: 8081

spring:
  application:
    name: recommended-service
  
logging:
  level:
    root: WARN
    com.books.recommendedservice: INFO
    org.springframework.web.client: INFO
    org.springframework: WARN

bookservice:
  url: http://localhost:8080/api/books