server:
  port: 3000

spring:
  data:
    mongodb:
      host: books-mongo-srv
      port: 27017
      database: book
  application:
    name: bookservice

logging:
  level:
    root: WARN
    com.books.bookservice: INFO
    org.mongodb.driver: WARN
    org.springframework: WARN