server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book
  application:
    name: books-service

logging:
  level:
    root: WARN
    com.books.bookservice: INFO
    org.mongodb.driver: WARN
    org.springframework: WARN